### ISSUE TITLE
Deprecate the old research design artifacts

### ISSUE THREAD

**Issue by eckdanny-osi** [ca-cwds/design-system#110]
The repo Wiki is full of disinformation. Take it down. Also take down the GitHub IO site

**Comment by eckdanny-osi** [comment]
Opened an issue on https://github.com/ca-cwds/research-design/issues/13, but i don't think anyone's maintaining. Will have to call in a favor with DevOps probably...

**Comment by NagaPradeepGajula-osi** [comment]
the repo has been archived and this read-only from now. Also the github IO pages for this repo are now take down. 
**_Github IO pages current status_**
![screen shot 2018-10-31 at 9 55 36 am](https://user-images.githubusercontent.com/30534102/47811127-44dff080-dd02-11e8-9d1a-04baee6926e3.png)
**_Repo status to archive state_**
![screen shot 2018-10-31 at 11 40 04 am](https://user-images.githubusercontent.com/30534102/47811132-47dae100-dd02-11e8-953f-55dc0794a9c4.png)

Closing this issue.
