### ISSUE TITLE
Guide site broken in IE11

### ISSUE THREAD

**Issue by eckdanny-osi** [ca-cwds/design-system#227]
reported on behalf of @vikas199 

![screen_shot_2018-11-01_at_5 02 06_pm](https://user-images.githubusercontent.com/30477263/47894051-c6787100-de1d-11e8-82a2-92753c7c9ef5.png)

**Comment by eckdanny-osi** [comment]
The guide site is built on CRA@^2.x which uses `@babel/preset-env` (babel7) and should not require manual inclusion of polyfills (e.g.; `import @babel/polyfill`). 

I haven't looked into it, but I'd wager the culprit is in [the browserslist spec](https://github.com/ca-cwds/design-system/blob/52a6216112e78bd20d323353b83c8d91915fcde8/libs/www/package.json#L31).

try 

```diff
  "browserslist": [
    ">0.2%",
    "not dead",
-   "not ie <= 11",
+   "not ie <= 10",
    "not op_mini all"
  ]
```

**Comment by eckdanny-osi** [comment]
We updated to CRA@2 in #125 (3weeks ago today)

Guessing the guide site has been broken in IE11 since then. 😱😱😱

We aren't collecting traffic data (don't know who would even monitor it.) We don't have a GUI test suite (especially for driving IE11). There's no client-side error beaconing. **Are there some QA folks in the program we can lean on to help prevent this kind of thing in the future?**

There is _one_ person i engage with regularly in DesignOps who is a windows + ie11 user. They are on a 2week vacay atm. I dont see this as a coincidence.

**Comment by sunilb0575** [comment]
And also similar issue in IE11 browser, when using ```<Alert />``` component. 
![screen shot 2018-11-02 at 4 05 35 pm](https://user-images.githubusercontent.com/30049885/47945192-6df8b080-debd-11e8-86e7-b419ad5011c8.png)
