### ISSUE TITLE
Clarify commit msg format & changelog generation

### ISSUE THREAD

**Issue by eckdanny-osi** [ca-cwds/design-system#237]
We're released twice since #217 and i'm seeing not all PRs make it to `CHANGELOG` generation. Upon inspection, this _is_ the expected behavior, but i'll argue we're better off making this explicit e.g. in the README. See **sources below for details.

lerna defaults to Angular commit format. Something we should be aware:

* The [coventionalcommits spec](https://www.conventionalcommits.org/en/v1.0.0-beta.2/) and [angular msgFormat#`type`](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type) prefixes are merely conventional (you can use whatever you want) but _ONLY_ `[feat|fix|perf]` prefixes will be written to the CHANGELOG during publish
* Scopes may be optional, but they're provided almost every time. Whatever package they impact, plz identify

###  TODO

* [ ] Do we want _more_ prefixes captured in the CHANGELOG?
* [ ] Document (e.g.; link to angular commit msg format) the format in use for this project

### sources

`git log --oneline`:

```log
a4181c7 v0.3.8
bf5da3a fix(icons): no dynamic module resolution, fix build (#234)
2c415af chore: update lerna (#223)
d5cdcbb refactor: organize monorepo into libs and apps (#218)
d9c65bd chore: consistent formatting in mono CHANGELOG
9d05b0c Clean up changelog
52a6216 v0.3.7
46aa920 refactor(www): use macro to generate repo stats (#221)
863bee9 chore: fix pkgJson license fields (#219)
27df839 build: publish with lerna (#217)
```

vs. `CHANGELOG`: 

```md
All notable changes to this project will be documented in this file.
See [Conventional Commits](https://conventionalcommits.org) for commit guidelines.

## [0.3.8](https://github.com/ca-cwds/design-system/compare/v0.3.7...v0.3.8) (2018-11-05)

### Bug Fixes

* **icons:** no dynamic module resolution, fix build ([#234](https://github.com/ca-cwds/design-system/issues/234)) ([bf5da3a](https://github.com/ca-cwds/design-system/commit/bf5da3a))

## [0.3.7](https://github.com/ca-cwds/design-system/compare/v0.3.6...v0.3.7) (2018-10-31)

### Bug Fixes

- add build:watch to reactstrap pkg ([#216](https://github.com/ca-cwds/design-system/issues/216)) ([b505e88](https://github.com/ca-cwds/design-system/commit/b505e88))

## [0.3.6](https://github.com/ca-cwds/design-system/compare/v0.3.5...v0.3.6)
```

**Comment by mlipardo** [comment]
Discuss this with the team chlorine.
