### ISSUE TITLE
Page Size dropdown in Pagination component doesn't show a currently selected value

### ISSUE THREAD

**Issue by denys-davydov** [ca-cwds/design-system#262]
Page Size dropdown in Pagination component doesn't show a currently selected value

<img width="851" alt="dropdown_issue" src="https://user-images.githubusercontent.com/11778272/49119601-ca9d8000-f25d-11e8-9259-0c0a92949e63.png">

**Comment by eckdanny-osi** [comment]
This bug was introduced in #226 and #246 The react-select API changed (it _was_ a major semver change). Fix in #264
