### ISSUE TITLE
Regression: LoadingCards

### ISSUE THREAD

**Issue by eckdanny-osi** [ca-cwds/design-system#280]
We dont have this anymore, but we should.

Usage example in CANS: [link](https://github.com/ca-cwds/cans/blob/adba46e8b11033f1366b070913c324f07aae372c/app/javascript/Application/components/Staff/Supervisor/SubordinateCard.js#L9)

Old `Card` impl: [link](https://github.com/ca-cwds/design-system/blob/v0.2.0-alpha.21/packages/cwds-components/src/Cards/Card.jsx)

This was back when we had lots of `recompose` and HOCs for conditional rendering. 

Ship a dumb LoadingCard or GlimmerCardBody component for easy conditional rendering in the ds apps plz

**Comment by eckdanny-osi** [comment]
@wmitchell-cambria ^

**Comment by wmitchell-cambria** [comment]
Hypothetical usage, based on the linked usage example in CANS:

```javascript
const SubordinateCardWithLoadingCard = ({ loadingState, staff }) => {
 const isLoading = loadingState === LoadingState.updating
 return isLoading ? (
   <LoadingCard />
 ) : (
   <Card className={'card supervisor-card'}>
     <CardHeader>
       <CardTitle className={'card-title-fix'}>Assigned Staff</CardTitle>
     </CardHeader>
     <CardBody>
       <StaffTable staff={staff} />
     </CardBody>
   </Card>
 )
}

const SubordinateCardWithGlimmerCardBody = ({ loadingState, staff }) => {
 const isLoading = loadingState === LoadingState.updating
 return (
   <Card className={'card supervisor-card'}>
     <CardHeader>
       <CardTitle className={'card-title-fix'}>Assigned Staff</CardTitle>
     </CardHeader>
     {isLoading ? <GlimmerCardBody /> : <CardBody><StaffTable staff={staff} /></CardBody>}
   </Card>
 )
}
```
