### ISSUE TITLE
Automate publishing to npm

### ISSUE THREAD

**Issue by eckdanny-osi** [ca-cwds/design-system#3]
Remove the humans from publishing `@cwds/components` to npm. Ideally, start using `semantic-release` and setup CI (e.g.: travis) to publish the lib on each build from master. At minimum, this routine should be scripted somehow to reduce errors and improve repeatability.

**Comment by NagaPradeepGajula-osi** [comment]
closing this in favor of PR#[217](https://github.com/ca-cwds/design-system/pull/217)

**Comment by eckdanny-osi** [comment]
Re-opening. At present, we can _still_ only publish to npm by manual methods. Fastest/Easiest way to automate:

 1. CI (plenty of free SaaS options: [circleci](https://circleci.com/), [travis](https://travis-ci.org/), [codeship](https://codeship.com/), ...)
 1. SaaS read/write access granted to this repo (ca-cwds github org admin must enable)

#217 is solves the problem of having to manually provide semver bump/version, but at present the only way our npm packages actually ship is when one of us humans publishes them

**Comment by eckdanny-osi** [comment]
note: we can have a convo re: SaaS CI vs DIY Jenkins if that's a helpful next step...

@NagaPradeepGajula-osi @LotharII are we 3 empowered to decide and implement?

**Comment by eckdanny-osi** [comment]
captured
