### ISSUE TITLE
Are Toggles a thing in CARES?

### ISSUE THREAD

**Issue by eckdanny-osi** [ca-cwds/design-system#307]
Toggles have been sneaking into impl space and into comps... 

Original vantage was **no toggles!**. Rationale:

 - mutually exclusive binary options have a control: radios
 - mutually exclusive sets (n > 2) have controls: select/radio

What is the fate of this?

**Comment by NagaPradeepGajula-osi** [comment]
Confirm with designers on to implement the toggles in design-system. Based on outcome implement.

**Comment by NagaPradeepGajula-osi** [comment]
Contact designers Chilton and Matt Johnson as this is already implemented in CANS.
