### ISSUE TITLE
InfoTip

### ISSUE THREAD

**Issue by eckdanny-osi** [ca-cwds/design-system#309]
Ontology for `InfoTip`???

- `Tooltip` is intended for _flow-content_ (e.g.; a word or a few words)
- `Popover`s are for _block-content_ (e.g.; arbitrary dom, has heading/footer support, ...)

The `InfoTip` is essentially an inline-icon that toggles _one_ of the above... 

@vikas199 USE `Popover` for implementation (confirmed w/ (@)chilton & (@)matt)

* [x] Which is it? Both? Multiple components needed?
* [ ] Implement it in `@cwds/components`
* [ ] Document in `www`
* [ ] Design Validated

**Comment by NagaPradeepGajula-osi** [comment]
The following request is already implemented through @cwds/reactstrap in CANS. The same implementation needs to be hoisted in @cwds/components

**Comment by NagaPradeepGajula-osi** [comment]
^^^ would be the A/C for the Jira story

**Comment by eckdanny-osi** [comment]
updated OP with decisions from design team (use `Popover`. `Infotips` will have arbitrarily structured DOM... `Tooltips` are for _short, flow-content_
