### ISSUE TITLE
Modals

### ISSUE THREAD

**Issue by eckdanny-osi** [ca-cwds/design-system#311]
Modals with thematic context (e.g.; warn, error, info, ...) _should_ share more visual cues with `Alert`. `Modal` composition is near identical to `Card`

* [ ] No dropshadows? (global) reflexive upon Button alts

What is the Modal design spec?

**Comment by NagaPradeepGajula-osi** [comment]
Replicate the following for Modals https://cws-cares.netlify.com/components/alert

**Comment by eckdanny-osi** [comment]
related to #306

**Comment by eckdanny-osi** [comment]
closed by #342
