### ISSUE TITLE
unpublished lib for docs components

### ISSUE THREAD

**Issue by eckdanny-osi** [ca-cwds/design-system#340]
We may want to section off the "docs-only" (components which are not published in `@cwds/*` packages, only present in the guide site). The following applies:

- inconvenient relative imports
- scss DS imports
- build steps (e.g.; TS)

consider partitioning out the docs-only components to an unpublished package in `libs/`

**Comment by NagaPradeepGajula-osi** [comment]
@eckdanny-osi can we close this as its done via #351 ?
