### ISSUE TITLE
Standardize name for library

### ISSUE THREAD

**Issue by c-dunwoodie** [ca-cwds/design-system#71]
Many CWDS folks have gotten used to the term "Component Library." Recommend confirming "Design System" name works going forward.

Also, ensure name on browser tab matches actual site name.

**Comment by eckdanny-osi** [comment]
We should be explicit re diff "component library" and "design system" (they are NOT the same thing). Simple copy changes in guide site were made in #70

The broader idea of documenting Design System as a separate entity from Component Library (appropriately so) is captured #26 

closing.
