### ISSUE TITLE
What is CARES DS guide site?

### ISSUE THREAD

**Issue by eckdanny-osi** [ca-cwds/design-system#79]
Add an about section to the design system guide site dashboard to answer some high-level questions like why does this exist?

This section should clarify:

How is the design system guide site different from a general purpose UI framework docs site?

Is this also a reference implementation for digital service teams?

Is the value to the program as a library or as configuration of common libraries usage?

what is the difference between a design system and a component Library?

**Comment by eckdanny-osi** [comment]
I'm ooo today, but got more slack DMs from non-technical stakeholders seeking disambiguation b/n "component library", "pattern library", "design system", "UI framework"...

The doc addition should clarify for all

**Comment by mlipardo** [comment]
irrelevant
